maintainer: "Jason Serviss"
email: "jason.serviss@ki.se"
from: "bioconductor/release_base2:R3.4.0_Bioc3.5"
pandoc: false
sysdeps:
  - imagemagick
  - libudunits2-dev
  - librsvg2-dev
  - pkg-config
  - libjpeg-dev
  - libtiff5-dev
bioc:
  - topGO
  - biomaRt
  - GOSim
  - AnnotationDbi
  - GO.db
cran:
  - Rtsne/0.13
  - ggthemes/3.4.0
  - liftr/0.7
  - igraph/1.0.1
  - magrittr/1.5
  - knitr/1.17
  - rmarkdown/1.6
  - testthat/1.0.2
  - multipanelfigure/0.9.0
  - gtable/0.2.0
  - ggraph/1.0.0
  - printr/0.1
  - ggplot2/2.2.1
  - tibble/1.3.4
  - dplyr/0.7.4
  - stringr/1.2.0
  - purrr/0.2.4
remotes:
  - "jasonserviss/acidAdaptedRNAseq"
